### ISSUE TITLE
Add Dip-Switch Position to Electrical Wiring Schematic

### ISSUE THREAD

**Issue by mikelovic** [Open-Lab-Starter-Kit/OLSK-Large-Laser#1]
https://github.com/Open-Lab-Starter-Kit/OLSK-Large-Laser/blob/main/OLSK_Large_Laser_V1_WiringSchematic_Board2022.pdf

would be helpful to add the information of dip-switches position of the 2 motor drivers X, Y.

**Comment by licash** [comment]
The dip switches position was added to the wiring schematic.
